apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rich-demo.fullname" . }}
  labels:
    {{- include "rich-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rich-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rich-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "rich-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.containerPort | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}